export const config = {
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION,
  S3_BUCKET: process.env.S3_BUCKET,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  MONGODB_URI: process.env.MONGODB_URI,
  MAX_FILE_SIZE_BYTES: 25 * 1024 * 1024,
  MAX_FILE_COUNT: 10,
};
